### ISSUE TITLE
Task "webpack:debug" failed: Cannot resolve 'file' or 'directory'

### ISSUE THREAD

**Issue by DanielRoeven** [madebymany/sir-trevor-js#382]
I am trying to set up Sir Trevor 0.5.0. When compiling for development (```npm run dev```), I get the following error (even though the directory ``src`` is clearly there):

```
> sir-trevor@0.5.0 dev /Users/daniel/Downloads/SirTrevTest/bower_components/sir-trevor-js
> grunt dev watch

Running "sass:dist" (sass) task

Running "sass:test" (sass) task

Running "webpack:debug" (webpack) task
Version: webpack 1.12.0     
              Asset     Size  Chunks             Chunk Names
sir-trevor.debug.js  1.95 kB       0  [emitted]  main

ERROR in ./index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./src in /Users/daniel/Downloads/SirTrevTest/bower_components/sir-trevor-js
 @ ./index.js 1:17-33
Warning: Task "webpack:debug" failed. Use --force to continue.

Aborted due to warnings.

npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! sir-trevor@0.5.0 dev: `grunt dev watch`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the sir-trevor@0.5.0 dev script 'grunt dev watch'.
npm ERR! This is most likely a problem with the sir-trevor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt dev watch
npm ERR! You can get their info via:
npm ERR!     npm owner ls sir-trevor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/daniel/Downloads/SirTrevTest/bower_components/sir-trevor-js/npm-debug.log
```

``index.js`` looks like this:
```
module.exports = require('./src');
```

``webpack.config.js`` looks like this:
```
module.exports = {
	module: {
		loaders: [
			{ test: /\.css$/, loader: "style!css" },
			{ test: /\.jade$/, loader: "jade?self" }
		]
	},
	node: {
		fs: "empty"
	}
}
```

And finally, ``npm-debug.log`` looks like this:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev sir-trevor@0.5.0
6 info dev sir-trevor@0.5.0
7 verbose unsafe-perm in lifecycle true
8 info sir-trevor@0.5.0 Failed to exec dev script
9 verbose stack Error: sir-trevor@0.5.0 dev: `grunt dev watch`
9 verbose stack Exit status 3
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid sir-trevor@0.5.0
11 verbose cwd /Users/daniel/Downloads/SirTrevTest/bower_components/sir-trevor-js
12 error Darwin 14.1.0
13 error argv "node" "/usr/local/bin/npm" "run" "dev"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error sir-trevor@0.5.0 dev: `grunt dev watch`
17 error Exit status 3
18 error Failed at the sir-trevor@0.5.0 dev script 'grunt dev watch'.
18 error This is most likely a problem with the sir-trevor package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     grunt dev watch
18 error You can get their info via:
18 error     npm owner ls sir-trevor
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
 ```

What could be causing this error?

**Comment by raffij** [comment]
Hi @DanielRoeven,

The bower package is meant for distribution rather than for development.
The package strips out the src files apart from blocks, as you'll see in the bower.json file.

https://github.com/madebymany/sir-trevor-js/blob/master/bower.json

If you want to access the entire package then you could `npm install sir-trevor` instead.

Let me know what you are trying to achieve and maybe I can help further.

**Comment by DanielRoeven** [comment]
(Let me preface this by thanking you for the quick response and admitting that I'm not entirely familiar with the large suite of Javascript packages used in Sir Trevor.)

For now, I'm just trying to get the example index.html ()to run.

What I've done is install Sir Trevor following the steps in the documentation: install Sir Trevor using ``bower install`` (with a ``bower.json`` file), then installing necessary dependencies via ``npm install``, and finally running ``npm test`` (as mentioned in the Readme).

**Comment by raffij** [comment]
Ok.

Sounds like we need to separate the docs slightly and update the examples with a dist version.

At present the examples/index.html is looking at the debug assets.

`bower install sir-trevor` is not going to do what you want for now.

If you want to test sir-trevor then i'd suggest.

```
npm install sir-trevor
cd node_modules/sir-trevor
npm install
npm run dev
open examples/index.html
```

What you could also do for now is modify the ./examples/index.html to link to the root dir of the package rather than build dir.

**Comment by DanielRoeven** [comment]
Great, that works perfectly! Thank you.
